"""Car data for SwipeStack — hot hatches and off-roaders."""

MODEL_MAP = {
    # Hot Hatches
    "Audi RS3": ("Audi", "RS 3"),
    "Audi S3": ("Audi", "S3"),
    "CUPRA Ateca": ("CUPRA", None),  # EU-only
    "Honda Civic Hatchback": ("Honda", "Civic 4Dr"),
    "Honda Civic Hatchback Hybrid": ("Honda", "Civic Hybrid"),
    "Hyundai i30": ("Hyundai", None),  # EU-only
    "Hyundai Veloster": ("Hyundai", "Veloster"),
    "Kia Ceed": ("Kia", None),  # EU-only
    "Kia Stinger": ("Kia", "Stinger RWD"),
    "SEAT Leon": ("SEAT", None),  # EU-only
    "Skoda Octavia RS": ("Skoda", None),  # EU-only
    "Volkswagen Golf GTD": ("Volkswagen", None),  # EU-only
    "Volkswagen Golf GTI": ("Volkswagen", "GTI"),
    "Volkswagen Golf R": ("Volkswagen", "Golf R"),
    "Volkswagen Jetta GLI": ("Volkswagen", "Jetta GLI"),
    "Volkswagen Polo GTI": ("Volkswagen", None),  # EU-only
    # Off-Roaders
    "Chevrolet Silverado 1500": ("Chevrolet", "Silverado 1500 4WD"),
    "Dodge Durango": ("Dodge", "Durango AWD"),
    "Ford Bronco Sport": ("Ford", "Bronco Sport 4WD"),
    "Ford Expedition": ("Ford", "Expedition 4WD"),
    "Ford Explorer": ("Ford", "Explorer AWD"),
    "Ford Explorer Hybrid": ("Ford", "Explorer Hybrid AWD"),
    "Ford F-150": ("Ford", "F150 Pickup 4WD"),
    "Ford F-150 Hybrid": ("Ford", "F150 Pickup 4WD"),
    "Ford Maverick": ("Ford", "Maverick AWD"),
    "Ford Maverick Hybrid": ("Ford", "Maverick FWD"),
    "Ford Ranger": ("Ford", "Ranger 4WD"),
    "Genesis GV70": ("Genesis", "GV70 AWD"),
    "Genesis GV70 Electrified": ("Genesis", "GV70 Electrified AWD"),
    "Genesis GV80": ("Genesis", "GV80 AWD"),
    "GMC Sierra 1500": ("GMC", "Sierra 1500 4WD"),
    "Hyundai Palisade": ("Hyundai", "Palisade AWD"),
    "Hyundai Santa Cruz": ("Hyundai", "Santa Cruz AWD"),
    "Hyundai Santa Fe": ("Hyundai", "Santa Fe AWD"),
    "Hyundai Santa Fe Hybrid": ("Hyundai", "Santa Fe Hybrid AWD"),
    "Hyundai Santa Fe Plug-in Hybrid": ("Hyundai", "Santa Fe Plug-in Hybrid AWD"),
    "Hyundai Tucson": ("Hyundai", "Tucson AWD"),
    "Hyundai Tucson Diesel": ("Hyundai", None),  # EU-only
    "Hyundai Tucson Hybrid": ("Hyundai", "Tucson Hybrid AWD"),
    "Hyundai Tucson Plug-in Hybrid": ("Hyundai", "Tucson Plug-in Hybrid AWD"),
    "Jeep Grand Cherokee": ("Jeep", "Grand Cherokee 4WD"),
    "Kia Sorento": ("Kia", "Sorento AWD"),
    "Kia Sorento Hybrid": ("Kia", "Sorento Hybrid AWD"),
    "Kia Sorento Plug-in Hybrid": ("Kia", "Sorento Plug-in Hybrid AWD"),
    "Kia Telluride": ("Kia", "Telluride AWD"),
    "Lincoln Aviator": ("Lincoln", "Aviator AWD"),
    "Lincoln Aviator Plug-in Hybrid": ("Lincoln", "Aviator Plug-in Hybrid AWD"),
    "Ram 1500": ("Ram", "1500 4WD"),
    "Rivian R1S": ("Rivian", None),
    "Rivian R1T": ("Rivian", None),
    "Subaru Ascent": ("Subaru", "Ascent AWD"),
    "Subaru Crosstrek": ("Subaru", "Crosstrek AWD"),
    "Subaru Forester": ("Subaru", "Forester AWD"),
    "Subaru Outback": ("Subaru", "Outback AWD"),
    "Subaru XV": ("Subaru", "Crosstrek AWD"),  # XV = Crosstrek in US
    "Skoda Karoq": ("Skoda", None),  # EU-only
    "Skoda Kodiaq": ("Skoda", None),  # EU-only
    "Skoda Octavia Scout": ("Skoda", None),  # EU-only
    "Toyota Highlander": ("Toyota", "Highlander AWD"),
    "Toyota Highlander Hybrid": ("Toyota", "Highlander Hybrid AWD"),
    "Toyota RAV4": ("Toyota", "RAV4 AWD"),
    "Toyota RAV4 Hybrid": ("Toyota", "RAV4 Hybrid AWD"),
    "Volkswagen Atlas": ("Volkswagen", "Atlas 4MOTION"),
    "Volkswagen Atlas Cross Sport": ("Volkswagen", "Atlas Cross Sport 4MOTION"),
    "Volkswagen Tiguan": ("Volkswagen", "Tiguan 4MOTION"),
    "Volkswagen Tiguan eHybrid": ("Volkswagen", None),  # EU-only
}

CAR_DATA = {
    # =========================================================================
    # HOT HATCHES
    # =========================================================================
    "Audi RS3": {
        "reliability": "3/5",
        "fun_factor": "5/5",
        "zero_to_sixty": "3.6s",
        "engine": "2.5L Turbo I5",
        "driven_wheels": "AWD",
        "est_price_range": "$35k-$42k",
        "power_hp": "401 hp",
        "description": "Five-cylinder monster that sounds like nothing else on the road.",
        "pros": [
            "Legendary 2.5L 5-cylinder engine note",
            "Blistering acceleration with quattro grip",
            "Premium interior quality",
        ],
        "cons": [
            "Expensive for the segment",
            "Firm ride on rough roads",
            "Heavy for a hot hatch",
        ],
    },
    "Audi S3": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "4.4s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$18k-$24k",
        "power_hp": "306 hp",
        "description": "Refined all-weather performer that doubles as a daily driver.",
        "pros": [
            "AWD confidence in all conditions",
            "Strong turbo four with quick shifts",
            "Subtle styling flies under the radar",
        ],
        "cons": [
            "Understeer-prone in hard cornering",
            "Virtual cockpit can be distracting",
            "Numb steering feel",
        ],
    },
    "CUPRA Ateca": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.2s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "€22k-€30k",
        "power_hp": "300 hp",
        "description": "Spanish-tuned crossover with genuine hot hatch DNA.",
        "pros": [
            "SUV practicality with hot hatch performance",
            "Punchy 300 hp turbo four",
            "Sharp handling for a crossover",
        ],
        "cons": [
            "Not available in the US",
            "Interior quality trails German rivals",
            "Firm suspension compromises comfort",
        ],
    },
    "Honda Civic Hatchback": {
        "reliability": "5/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.2s",
        "engine": "2.0L I4",
        "driven_wheels": "FWD",
        "est_price_range": "$14k-$19k",
        "power_hp": "158 hp",
        "description": "The benchmark compact with unbeatable reliability and a manual option.",
        "pros": [
            "Bulletproof Honda reliability",
            "Available 6-speed manual",
            "Excellent cargo space for the class",
        ],
        "cons": [
            "Base engine is leisurely",
            "Road noise at highway speeds",
            "Infotainment learning curve",
        ],
    },
    "Honda Civic Hatchback Hybrid": {
        "reliability": "5/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.8s",
        "engine": "2.0L I4 Hybrid",
        "driven_wheels": "FWD",
        "est_price_range": "$24k-$28k",
        "power_hp": "200 hp",
        "description": "Fuel-sipping hybrid that still looks sharp and drives well.",
        "pros": [
            "Exceptional fuel economy (~50 mpg combined)",
            "Smooth hybrid powertrain",
            "Honda reliability with lower running costs",
        ],
        "cons": [
            "No manual transmission option",
            "Less engaging to drive than standard Civic",
            "Premium over base model is significant",
        ],
    },
    "Hyundai i30": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "8.0s",
        "engine": "1.5L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "€12k-€18k",
        "power_hp": "160 hp",
        "description": "European-market hatchback with mature handling and solid value.",
        "pros": [
            "Excellent value for money",
            "Composed highway cruiser",
            "5-year unlimited mileage warranty",
        ],
        "cons": [
            "Not sold in North America",
            "Styling is conservative",
            "N-Line is sporty-looking but not truly fast",
        ],
    },
    "Hyundai Veloster": {
        "reliability": "4/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.0s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "$18k-$24k",
        "power_hp": "275 hp",
        "description": "Quirky three-door layout with N performance that punches above its price.",
        "pros": [
            "Veloster N is a riot to drive",
            "Asymmetric doors are practical and unique",
            "Strong value vs. European rivals",
        ],
        "cons": [
            "Discontinued after 2023",
            "Rear seat access is awkward",
            "Road and wind noise intrusion",
        ],
    },
    "Kia Ceed": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.5s",
        "engine": "1.5L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "€14k-€20k",
        "power_hp": "160 hp",
        "description": "Practical European hatchback with a long warranty and easy manners.",
        "pros": [
            "7-year warranty",
            "Comfortable ride quality",
            "Spacious interior for the class",
        ],
        "cons": [
            "Not available in the US",
            "Bland driving dynamics",
            "Infotainment lags behind rivals",
        ],
    },
    "Kia Stinger": {
        "reliability": "4/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "4.7s",
        "engine": "3.3L Twin-Turbo V6",
        "driven_wheels": "RWD",
        "est_price_range": "$20k-$28k",
        "power_hp": "368 hp",
        "description": "Gran turismo that brought rear-drive sport sedan thrills at a bargain.",
        "pros": [
            "Twin-turbo V6 is a proper powerhouse",
            "RWD-based platform with great balance",
            "Hatchback practicality in a sedan body",
        ],
        "cons": [
            "Discontinued after 2023",
            "Interior doesn't match German rivals",
            "Depreciation can be steep",
        ],
    },
    "SEAT Leon": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "6.4s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "€8k-€14k",
        "power_hp": "245 hp",
        "description": "Spanish cousin of the Golf GTI with sharper looks and sportier tuning.",
        "pros": [
            "More aggressive styling than the Golf",
            "Sharp chassis with precise steering",
            "Available estate body style",
        ],
        "cons": [
            "Not available outside Europe",
            "VW group parts-bin interior",
            "Reliability mirrors VW group average",
        ],
    },
    "Skoda Octavia RS": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.9s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "€16k-€22k",
        "power_hp": "245 hp",
        "description": "The practical choice: fast estate with massive cargo space.",
        "pros": [
            "Huge boot space, especially in estate form",
            "Golf GTI mechanicals at a lower price",
            "Understated sleeper looks",
        ],
        "cons": [
            "Not available in North America",
            "Lacks the GTI's brand cachet",
            "DSG gearbox can be jerky at low speeds",
        ],
    },
    "Volkswagen Golf GTD": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.1s",
        "engine": "2.0L Turbo Diesel I4",
        "driven_wheels": "FWD",
        "est_price_range": "€10k-€16k",
        "power_hp": "200 hp",
        "description": "Diesel GTI alternative for high-mileage European drivers.",
        "pros": [
            "Exceptional highway fuel economy",
            "Strong low-end torque",
            "Refined cruiser on long trips",
        ],
        "cons": [
            "Not sold in North America",
            "Less exciting than the GTI",
            "Diesel stigma post-Dieselgate",
        ],
    },
    "Volkswagen Golf GTI": {
        "reliability": "3/5",
        "fun_factor": "5/5",
        "zero_to_sixty": "5.1s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "$12k-$18k",
        "power_hp": "241 hp",
        "description": "The original hot hatch, still the benchmark after nearly 50 years.",
        "pros": [
            "Perfect balance of fun and daily usability",
            "Iconic heritage with modern tech",
            "Available manual transmission",
        ],
        "cons": [
            "VW reliability concerns long-term",
            "Torque steer under hard acceleration",
            "Options can push price up quickly",
        ],
    },
    "Volkswagen Golf R": {
        "reliability": "3/5",
        "fun_factor": "5/5",
        "zero_to_sixty": "4.4s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$22k-$28k",
        "power_hp": "315 hp",
        "description": "AWD Golf with drift mode and supercar-baiting acceleration.",
        "pros": [
            "All-weather performance with torque vectoring",
            "Drift mode for track day fun",
            "Sleeper looks hide serious speed",
        ],
        "cons": [
            "Expensive for a Golf",
            "Capacitive touch buttons are frustrating",
            "Harsh ride in sport mode",
        ],
    },
    "Volkswagen Jetta GLI": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.6s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "$22k-$27k",
        "power_hp": "228 hp",
        "description": "GTI performance in a sedan body with a trunk and a lower price.",
        "pros": [
            "GTI powertrain at a lower cost",
            "Traditional trunk for easier loading",
            "Available 6-speed manual",
        ],
        "cons": [
            "Less refined interior than the GTI",
            "Torsion beam rear suspension",
            "Styling is subdued compared to competitors",
        ],
    },
    "Volkswagen Polo GTI": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "6.5s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "€14k-€20k",
        "power_hp": "207 hp",
        "description": "Mini GTI for tight European streets with peppy turbo power.",
        "pros": [
            "Nimble city car with real punch",
            "More affordable entry to GTI family",
            "Light weight aids handling",
        ],
        "cons": [
            "Not sold in North America",
            "Cramped rear seats",
            "DSG-only, no manual option",
        ],
    },
    # =========================================================================
    # OFF-ROADERS
    # =========================================================================
    "Chevrolet Silverado 1500": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.1s",
        "engine": "5.3L V8",
        "driven_wheels": "4WD",
        "est_price_range": "$28k-$36k",
        "ground_clearance": "8.9 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "11,500 lbs",
        "description": "Full-size workhorse with V8 grunt and massive towing muscle.",
        "pros": [
            "Huge towing and payload capacity",
            "Proven V8 reliability",
            "Wide range of trims for every budget",
        ],
        "cons": [
            "Interior quality lags Ram and Ford",
            "Thirsty V8 fuel economy",
            "Enormous footprint for urban driving",
        ],
    },
    "Dodge Durango": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "6.2s",
        "engine": "3.6L V6",
        "driven_wheels": "AWD",
        "est_price_range": "$26k-$34k",
        "ground_clearance": "8.1 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "8,700 lbs",
        "description": "Muscle-car-meets-SUV with available Hellcat power and three rows.",
        "pros": [
            "Best-in-class towing for a three-row SUV",
            "SRT and Hellcat trims are absurd fun",
            "Aggressive styling stands out",
        ],
        "cons": [
            "Aging platform and interior design",
            "Fuel economy is poor across the range",
            "Third row is tight for adults",
        ],
    },
    "Ford Bronco Sport": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "6.5s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "4WD",
        "est_price_range": "$22k-$28k",
        "ground_clearance": "8.8 in",
        "four_wd_type": "Full-Time 4WD",
        "tow_capacity": "2,200 lbs",
        "description": "Trail-ready compact SUV with serious off-road chops in a small package.",
        "pros": [
            "Surprisingly capable off-road for its size",
            "Rugged retro styling",
            "Badlands trim has a twin-clutch rear diff",
        ],
        "cons": [
            "Not as spacious as the full Bronco",
            "Base engine is underpowered",
            "Towing capacity is limited",
        ],
    },
    "Ford Expedition": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "5.9s",
        "engine": "3.5L Twin-Turbo V6",
        "driven_wheels": "4WD",
        "est_price_range": "$42k-$52k",
        "ground_clearance": "9.8 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "9,300 lbs",
        "description": "Full-size family hauler with three rows and serious towing ability.",
        "pros": [
            "Massive interior space for passengers and cargo",
            "Strong twin-turbo V6 towing power",
            "Independent rear suspension for smooth ride",
        ],
        "cons": [
            "Fuel economy is dismal",
            "Expensive when optioned up",
            "Too large for tight parking situations",
        ],
    },
    "Ford Explorer": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "5.6s",
        "engine": "2.3L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$22k-$30k",
        "ground_clearance": "7.9 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,600 lbs",
        "description": "America's best-selling three-row SUV with a turbo four or twin-turbo V6.",
        "pros": [
            "Spacious three-row seating",
            "Available twin-turbo V6 for ST trim",
            "Decent towing for a midsize SUV",
        ],
        "cons": [
            "Infotainment can be glitchy",
            "Early model year reliability issues",
            "Third row is cramped",
        ],
    },
    "Ford Explorer Hybrid": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.9s",
        "engine": "3.3L V6 Hybrid",
        "driven_wheels": "AWD",
        "est_price_range": "$26k-$34k",
        "ground_clearance": "7.9 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,000 lbs",
        "description": "Three-row hybrid that cuts fuel costs without sacrificing space.",
        "pros": [
            "Significantly better fuel economy than gas Explorer",
            "Same interior space as standard model",
            "Smooth hybrid powertrain",
        ],
        "cons": [
            "Less towing capacity than gas V6",
            "Hybrid premium adds to base price",
            "Battery takes some cargo floor space",
        ],
    },
    "Ford F-150": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.3s",
        "engine": "3.5L Twin-Turbo V6",
        "driven_wheels": "4WD",
        "est_price_range": "$28k-$38k",
        "ground_clearance": "9.4 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "13,500 lbs",
        "description": "America's best-selling vehicle for decades, and for good reason.",
        "pros": [
            "Massive towing and payload capacity",
            "Aluminum body saves weight",
            "Enormous range of trims and configurations",
        ],
        "cons": [
            "Fuel economy suffers with the V6 turbo",
            "High-trim prices rival luxury trucks",
            "Ride quality is truck-firm on rough roads",
        ],
    },
    "Ford F-150 Hybrid": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "5.7s",
        "engine": "3.5L Twin-Turbo V6 Hybrid (PowerBoost)",
        "driven_wheels": "4WD",
        "est_price_range": "$32k-$42k",
        "ground_clearance": "9.4 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "12,700 lbs",
        "description": "PowerBoost hybrid adds a mobile generator and better mpg to the F-150.",
        "pros": [
            "Pro Power Onboard is a rolling generator",
            "Best-in-class hybrid truck fuel economy",
            "Still tows over 12,000 lbs",
        ],
        "cons": [
            "Hybrid premium is substantial",
            "Complex powertrain may cost more to repair",
            "Only available on higher trims",
        ],
    },
    "Ford Maverick": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.4s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$22k-$28k",
        "ground_clearance": "8.6 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "4,000 lbs",
        "description": "Compact truck that parks like a car but hauls like it means it.",
        "pros": [
            "Unibody construction rides like a car",
            "Incredible value for a new truck",
            "Versatile bed with DIY-friendly slots",
        ],
        "cons": [
            "Bed is small for serious hauling",
            "Rear seat is tight for tall passengers",
            "High demand leads to markups",
        ],
    },
    "Ford Maverick Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.6s",
        "engine": "2.5L I4 Hybrid",
        "driven_wheels": "FWD",
        "est_price_range": "$20k-$26k",
        "ground_clearance": "8.6 in",
        "four_wd_type": None,
        "tow_capacity": "2,000 lbs",
        "description": "42 mpg city in a pickup truck. Not a typo.",
        "pros": [
            "Best fuel economy of any pickup, period",
            "Lowest starting price in the truck segment",
            "Practical for urban truck needs",
        ],
        "cons": [
            "FWD only, no AWD option for hybrid",
            "Towing limited to 2,000 lbs",
            "CVT can drone under heavy acceleration",
        ],
    },
    "Ford Ranger": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "6.8s",
        "engine": "2.3L Turbo I4",
        "driven_wheels": "4WD",
        "est_price_range": "$30k-$36k",
        "ground_clearance": "8.9 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "7,500 lbs",
        "description": "Midsize truck with genuine off-road capability and manageable size.",
        "pros": [
            "More maneuverable than full-size trucks",
            "Strong towing for a midsize",
            "Available Tremor off-road package",
        ],
        "cons": [
            "Interior is dated compared to rivals",
            "Ride quality is stiff unladen",
            "Rear seat space is limited in SuperCab",
        ],
    },
    "Genesis GV70": {
        "reliability": "4/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.1s",
        "engine": "2.5L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$30k-$38k",
        "ground_clearance": "7.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Luxury sport SUV that embarrasses German rivals at a lower price.",
        "pros": [
            "Stunning exterior and interior design",
            "Powerful turbo engine with sport tuning",
            "5-year bumper-to-bumper warranty",
        ],
        "cons": [
            "Cargo space is smaller than rivals",
            "Infotainment takes time to learn",
            "Brand awareness is still growing",
        ],
    },
    "Genesis GV70 Electrified": {
        "reliability": "4/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "4.2s",
        "engine": "Dual Electric Motors",
        "driven_wheels": "AWD",
        "est_price_range": "$32k-$40k",
        "ground_clearance": "7.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Electric luxury SUV with 429 hp and rapid 800V charging.",
        "pros": [
            "800V architecture for ultra-fast charging",
            "429 hp dual-motor AWD is quick",
            "Luxurious interior with no gas costs",
        ],
        "cons": [
            "236-mile range is modest for an EV",
            "Heavy battery adds weight",
            "Charging network not as robust as Tesla",
        ],
    },
    "Genesis GV80": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "5.5s",
        "engine": "2.5L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$42k-$50k",
        "ground_clearance": "7.7 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "6,000 lbs",
        "description": "Full-size luxury SUV that undercuts BMW X5 while matching its quality.",
        "pros": [
            "Opulent interior with quilted leather",
            "Available 3.5L twin-turbo V6",
            "Strong value vs. German luxury SUVs",
        ],
        "cons": [
            "Third row is very tight",
            "Fuel economy is mediocre",
            "Resale value still unproven",
        ],
    },
    "GMC Sierra 1500": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.0s",
        "engine": "5.3L V8",
        "driven_wheels": "4WD",
        "est_price_range": "$28k-$38k",
        "ground_clearance": "8.9 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "11,800 lbs",
        "description": "Premium-trimmed Silverado sibling with the MultiPro tailgate.",
        "pros": [
            "MultiPro tailgate is genuinely useful",
            "Denali and AT4 trims are luxurious",
            "Strong V8 towing performance",
        ],
        "cons": [
            "Expensive when loaded with options",
            "CarbonPro bed is pricey",
            "Poor fuel economy with the V8",
        ],
    },
    "Hyundai Palisade": {
        "reliability": "4/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.0s",
        "engine": "3.8L V6",
        "driven_wheels": "AWD",
        "est_price_range": "$26k-$34k",
        "ground_clearance": "7.9 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,000 lbs",
        "description": "Three-row family hauler that feels like a luxury SUV at a mainstream price.",
        "pros": [
            "Exceptionally quiet and comfortable cabin",
            "Generous standard features",
            "Spacious third row that adults can use",
        ],
        "cons": [
            "V6 feels underpowered when fully loaded",
            "Not sporty or exciting to drive",
            "Dealer markups have been rampant",
        ],
    },
    "Hyundai Santa Cruz": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.6s",
        "engine": "2.5L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$24k-$30k",
        "ground_clearance": "8.6 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,000 lbs",
        "description": "Sport adventure vehicle that blurs the line between SUV and pickup.",
        "pros": [
            "Lockable tonneau cover for secure storage",
            "Drives like a crossover, hauls like a truck",
            "Turbo engine has real punch",
        ],
        "cons": [
            "Bed is tiny for serious truck work",
            "Rear seat legroom is tight",
            "Polarizing styling",
        ],
    },
    "Hyundai Santa Fe": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.6s",
        "engine": "2.5L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$18k-$24k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Boldly redesigned two-row SUV with boxy looks and big interior space.",
        "pros": [
            "Striking new design stands out in traffic",
            "Surprisingly spacious cargo area",
            "Strong turbo engine is standard",
        ],
        "cons": [
            "Ride can be firm on rough roads",
            "No third-row option anymore",
            "Infotainment screen placement is unusual",
        ],
    },
    "Hyundai Santa Fe Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.8s",
        "engine": "1.6L Turbo I4 Hybrid",
        "driven_wheels": "AWD",
        "est_price_range": "$26k-$32k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "Fuel-efficient Santa Fe that sips gas without sacrificing space.",
        "pros": [
            "~37 mpg combined is excellent for an SUV",
            "Same bold styling as gas model",
            "AWD is standard",
        ],
        "cons": [
            "Towing drops to 2,000 lbs",
            "Turbo-hybrid powertrain has lag",
            "Higher price than base gas model",
        ],
    },
    "Hyundai Santa Fe Plug-in Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.5s",
        "engine": "1.6L Turbo I4 PHEV",
        "driven_wheels": "AWD",
        "est_price_range": "$28k-$35k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "30+ miles of electric range for commuters who want an SUV.",
        "pros": [
            "~30 miles EV range covers most commutes",
            "Federal tax credit eligible",
            "All-electric driving around town",
        ],
        "cons": [
            "Heavy battery adds weight",
            "Cargo space slightly reduced",
            "Charging infrastructure still growing",
        ],
    },
    "Hyundai Tucson": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.7s",
        "engine": "2.5L I4",
        "driven_wheels": "AWD",
        "est_price_range": "$20k-$26k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "Sharp-looking compact SUV with angular styling and solid value.",
        "pros": [
            "Bold parametric design language",
            "Generous standard safety features",
            "Comfortable ride quality",
        ],
        "cons": [
            "Base engine feels sluggish",
            "Infotainment can be laggy",
            "Towing is limited to 2,000 lbs",
        ],
    },
    "Hyundai Tucson Diesel": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "9.5s",
        "engine": "2.0L Turbo Diesel I4",
        "driven_wheels": "AWD",
        "est_price_range": "€16k-€22k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "3,900 lbs",
        "description": "European diesel variant built for long highway hauls.",
        "pros": [
            "Excellent highway fuel economy",
            "Strong low-end torque for towing",
            "Well-suited for European driving patterns",
        ],
        "cons": [
            "Not available in North America",
            "Diesel is slower to accelerate",
            "Higher maintenance costs than petrol",
        ],
    },
    "Hyundai Tucson Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.4s",
        "engine": "1.6L Turbo I4 Hybrid",
        "driven_wheels": "AWD",
        "est_price_range": "$24k-$30k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "Best-selling compact SUV hybrid with 38 mpg combined.",
        "pros": [
            "~38 mpg combined is class-leading",
            "Same sharp styling as gas model",
            "AWD standard on all hybrid trims",
        ],
        "cons": [
            "Transmission can be hesitant",
            "No significant performance improvement",
            "Limited towing capacity",
        ],
    },
    "Hyundai Tucson Plug-in Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.0s",
        "engine": "1.6L Turbo I4 PHEV",
        "driven_wheels": "AWD",
        "est_price_range": "$32k-$38k",
        "ground_clearance": "8.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "33 miles of electric range in a compact SUV package.",
        "pros": [
            "33-mile EV range for daily commutes",
            "261 hp combined system output",
            "Federal tax credit eligible",
        ],
        "cons": [
            "Price premium over hybrid is significant",
            "Charging adds daily routine step",
            "Cargo floor is slightly raised",
        ],
    },
    "Jeep Grand Cherokee": {
        "reliability": "2/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "6.0s",
        "engine": "3.6L V6",
        "driven_wheels": "4WD",
        "est_price_range": "$16k-$24k",
        "ground_clearance": "10.9 in",
        "four_wd_type": "Selectable Full-Time 4WD",
        "tow_capacity": "7,200 lbs",
        "description": "The luxury off-roader with Jeep's legendary trail capability.",
        "pros": [
            "Best-in-class off-road systems (Quadra-Trac II)",
            "Air suspension for adjustable ride height",
            "Premium interior in higher trims",
        ],
        "cons": [
            "Reliability has been below average",
            "Fuel economy is poor",
            "Electronics can be glitchy",
        ],
    },
    "Kia Sorento": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.0s",
        "engine": "2.5L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$18k-$24k",
        "ground_clearance": "7.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Three-row SUV that punches above its weight in features and style.",
        "pros": [
            "Three rows in a midsize footprint",
            "Strong turbo engine is responsive",
            "10-year/100k powertrain warranty",
        ],
        "cons": [
            "Third row is best for kids only",
            "Cargo space behind third row is tiny",
            "AWD not standard on all trims",
        ],
    },
    "Kia Sorento Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.6s",
        "engine": "1.6L Turbo I4 Hybrid",
        "driven_wheels": "AWD",
        "est_price_range": "$26k-$32k",
        "ground_clearance": "7.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "Three-row hybrid SUV that delivers 37 mpg with AWD standard.",
        "pros": [
            "~37 mpg combined with AWD",
            "Same three-row layout as gas model",
            "Smooth hybrid transitions",
        ],
        "cons": [
            "Towing drops significantly vs. gas model",
            "Some hesitation from the transmission",
            "Price premium over gas version",
        ],
    },
    "Kia Sorento Plug-in Hybrid": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.2s",
        "engine": "1.6L Turbo I4 PHEV",
        "driven_wheels": "AWD",
        "est_price_range": "$28k-$34k",
        "ground_clearance": "7.3 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "2,000 lbs",
        "description": "32 miles of electric range in a three-row family SUV.",
        "pros": [
            "32-mile EV range for short trips",
            "Federal tax credit eligible",
            "Three rows plus AWD plus plug-in",
        ],
        "cons": [
            "Heavy battery affects handling",
            "Limited towing at 2,000 lbs",
            "PHEV trims are expensive",
        ],
    },
    "Kia Telluride": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.8s",
        "engine": "3.8L V6",
        "driven_wheels": "AWD",
        "est_price_range": "$28k-$34k",
        "ground_clearance": "8.4 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,500 lbs",
        "description": "Full-size presence in a midsize package with a usable third row.",
        "pros": [
            "Best third row in the midsize class",
            "Premium look and feel throughout",
            "Strong towing for a unibody SUV",
        ],
        "cons": [
            "V6 can feel strained when fully loaded",
            "No turbo or hybrid option yet",
            "Dealer markups have been persistent",
        ],
    },
    "Lincoln Aviator": {
        "reliability": "2/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "5.4s",
        "engine": "3.0L Twin-Turbo V6",
        "driven_wheels": "AWD",
        "est_price_range": "$30k-$40k",
        "ground_clearance": "7.6 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,600 lbs",
        "description": "American luxury meets twin-turbo V6 power in a serene three-row cruiser.",
        "pros": [
            "400 hp twin-turbo V6 is effortless",
            "Whisper-quiet cabin",
            "Air suspension glides over rough roads",
        ],
        "cons": [
            "Reliability has been problematic",
            "Complex tech can be glitchy",
            "Depreciation is steep",
        ],
    },
    "Lincoln Aviator Plug-in Hybrid": {
        "reliability": "2/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "5.0s",
        "engine": "3.0L Twin-Turbo V6 PHEV",
        "driven_wheels": "AWD",
        "est_price_range": "$32k-$42k",
        "ground_clearance": "7.6 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,600 lbs",
        "description": "494 hp luxury PHEV with 21 miles of electric range.",
        "pros": [
            "494 hp combined output is exhilarating",
            "Electric-only mode for short trips",
            "All the Aviator luxury plus EV benefits",
        ],
        "cons": [
            "21-mile EV range is modest",
            "Reliability concerns carry over",
            "Very expensive when loaded",
        ],
    },
    "Ram 1500": {
        "reliability": "3/5",
        "fun_factor": "4/5",
        "zero_to_sixty": "5.9s",
        "engine": "5.7L V8",
        "driven_wheels": "4WD",
        "est_price_range": "$24k-$34k",
        "ground_clearance": "10.0 in",
        "four_wd_type": "Part-Time 4WD",
        "tow_capacity": "12,750 lbs",
        "description": "The comfort king of full-size trucks with a class-leading interior.",
        "pros": [
            "Best-in-class ride quality with coil springs",
            "Luxurious interior, especially in Longhorn/Limited",
            "Strong HEMI V8 towing capability",
        ],
        "cons": [
            "HEMI fuel economy is poor",
            "Heavy and large for urban use",
            "eTorque mild hybrid adds complexity",
        ],
    },
    "Rivian R1S": {
        "reliability": "3/5",
        "fun_factor": "5/5",
        "zero_to_sixty": "3.0s",
        "engine": "Quad Electric Motors",
        "driven_wheels": "AWD",
        "est_price_range": "$52k-$65k",
        "ground_clearance": "14.9 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "7,700 lbs",
        "description": "Electric adventure SUV with supercar speed and three rows.",
        "pros": [
            "Quad motors deliver insane acceleration",
            "Best-in-class ground clearance for an EV",
            "Three rows in a premium electric package",
        ],
        "cons": [
            "Expensive with limited trim options",
            "Charging infrastructure still maturing",
            "Build quality inconsistencies reported",
        ],
    },
    "Rivian R1T": {
        "reliability": "3/5",
        "fun_factor": "5/5",
        "zero_to_sixty": "3.0s",
        "engine": "Quad Electric Motors",
        "driven_wheels": "AWD",
        "est_price_range": "$48k-$60k",
        "ground_clearance": "14.9 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "11,000 lbs",
        "description": "Electric pickup that can outrun sports cars and crawl boulders.",
        "pros": [
            "Gear tunnel is a genius storage solution",
            "Quad motors with tank-turn capability",
            "Adventure-ready with camp kitchen option",
        ],
        "cons": [
            "Towing significantly reduces range",
            "Service network is still sparse",
            "Price puts it in luxury territory",
        ],
    },
    "Subaru Ascent": {
        "reliability": "3/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.6s",
        "engine": "2.4L Turbo Boxer H4",
        "driven_wheels": "AWD",
        "est_price_range": "$20k-$26k",
        "ground_clearance": "8.7 in",
        "four_wd_type": "Full-Time Symmetrical AWD",
        "tow_capacity": "5,000 lbs",
        "description": "Subaru's largest, a three-row family hauler with standard AWD.",
        "pros": [
            "Symmetrical AWD is standard",
            "Spacious three-row interior",
            "Strong safety ratings",
        ],
        "cons": [
            "CVT can drone and hesitate",
            "Fuel economy is mediocre for a four-cylinder",
            "Not exciting to drive",
        ],
    },
    "Subaru Crosstrek": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "8.3s",
        "engine": "2.5L Boxer H4",
        "driven_wheels": "AWD",
        "est_price_range": "$18k-$24k",
        "ground_clearance": "8.7 in",
        "four_wd_type": "Full-Time Symmetrical AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Compact crossover with serious ground clearance and standard AWD.",
        "pros": [
            "Best-in-class ground clearance for its size",
            "Symmetrical AWD handles all conditions",
            "Available manual transmission",
        ],
        "cons": [
            "Base engine is slow",
            "CVT drones at highway speeds",
            "Interior feels basic at lower trims",
        ],
    },
    "Subaru Forester": {
        "reliability": "4/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "8.0s",
        "engine": "2.5L Boxer H4",
        "driven_wheels": "AWD",
        "est_price_range": "$20k-$26k",
        "ground_clearance": "8.7 in",
        "four_wd_type": "Full-Time Symmetrical AWD",
        "tow_capacity": "1,500 lbs",
        "description": "Practical, safe, and capable all-weather crossover with great visibility.",
        "pros": [
            "Excellent outward visibility",
            "Standard AWD with X-MODE",
            "Top safety ratings across the board",
        ],
        "cons": [
            "Underpowered engine",
            "Towing capacity is very limited",
            "Road noise at highway speeds",
        ],
    },
    "Subaru Outback": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "6.1s",
        "engine": "2.5L Boxer H4",
        "driven_wheels": "AWD",
        "est_price_range": "$22k-$28k",
        "ground_clearance": "8.7 in",
        "four_wd_type": "Full-Time Symmetrical AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Lifted wagon that bridges the gap between car and SUV perfectly.",
        "pros": [
            "Wagon versatility with SUV ground clearance",
            "Available turbo boxer engine",
            "EyeSight safety suite is excellent",
        ],
        "cons": [
            "Base engine is adequate but not thrilling",
            "CVT transmission is uninspiring",
            "Interior materials are plain at base trims",
        ],
    },
    "Subaru XV": {
        "reliability": "4/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "8.3s",
        "engine": "2.0L Boxer H4",
        "driven_wheels": "AWD",
        "est_price_range": "€16k-€22k",
        "ground_clearance": "8.7 in",
        "four_wd_type": "Full-Time Symmetrical AWD",
        "tow_capacity": "1,500 lbs",
        "description": "The Crosstrek by its global name, same capability and value.",
        "pros": [
            "Excellent ground clearance for a compact",
            "Symmetrical AWD is standard",
            "Good resale value",
        ],
        "cons": [
            "2.0L engine feels underpowered",
            "CVT limits engagement",
            "Interior is functional, not fancy",
        ],
    },
    "Skoda Karoq": {
        "reliability": "3/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "8.4s",
        "engine": "1.5L Turbo I4",
        "driven_wheels": "FWD",
        "est_price_range": "€16k-€22k",
        "ground_clearance": "7.5 in",
        "four_wd_type": None,
        "tow_capacity": "2,200 lbs",
        "description": "Practical compact SUV built on VW bones with clever storage solutions.",
        "pros": [
            "VarioFlex rear seats are removable",
            "Solid VW Group mechanicals",
            "Good value vs. VW Tiguan",
        ],
        "cons": [
            "Not available in North America",
            "Bland to drive",
            "FWD-only on most trims",
        ],
    },
    "Skoda Kodiaq": {
        "reliability": "3/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.6s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "€18k-€26k",
        "ground_clearance": "7.7 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "4,400 lbs",
        "description": "Seven-seat SUV with VW Atlas DNA at a lower European price.",
        "pros": [
            "Seven seats with usable third row",
            "Strong towing for the class",
            "Clever storage throughout the cabin",
        ],
        "cons": [
            "Not sold in North America",
            "Diesel models being phased out",
            "Driving dynamics are utilitarian",
        ],
    },
    "Skoda Octavia Scout": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.8s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "€16k-€22k",
        "ground_clearance": "7.1 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "4,400 lbs",
        "description": "Lifted estate with AWD for light trails and muddy fields.",
        "pros": [
            "Massive boot space in estate form",
            "AWD with raised ride height",
            "Practical workhorse for rural roads",
        ],
        "cons": [
            "Not available in North America",
            "Not a real off-roader despite the look",
            "Interior is functional, not exciting",
        ],
    },
    "Toyota Highlander": {
        "reliability": "5/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.1s",
        "engine": "2.4L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$20k-$28k",
        "ground_clearance": "8.0 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "5,000 lbs",
        "description": "The reliable three-row choice that never lets families down.",
        "pros": [
            "Toyota reliability is unmatched",
            "Comfortable three-row seating",
            "Strong resale value",
        ],
        "cons": [
            "New turbo four lacks V6 smoothness",
            "Boring to drive",
            "Infotainment is basic compared to rivals",
        ],
    },
    "Toyota Highlander Hybrid": {
        "reliability": "5/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.3s",
        "engine": "2.5L I4 Hybrid",
        "driven_wheels": "AWD",
        "est_price_range": "$22k-$30k",
        "ground_clearance": "8.0 in",
        "four_wd_type": "Electronic AWD",
        "tow_capacity": "3,500 lbs",
        "description": "Fuel-efficient three-row that Toyota will still be making when the sun dies.",
        "pros": [
            "~36 mpg combined is excellent for a three-row",
            "Toyota hybrid reliability is legendary",
            "Electronic AWD with no driveshaft",
        ],
        "cons": [
            "Towing drops vs. gas model",
            "CVT can drone under load",
            "Not engaging to drive",
        ],
    },
    "Toyota RAV4": {
        "reliability": "5/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "8.0s",
        "engine": "2.5L I4",
        "driven_wheels": "AWD",
        "est_price_range": "$16k-$22k",
        "ground_clearance": "8.4 in",
        "four_wd_type": "Full-Time AWD",
        "tow_capacity": "3,500 lbs",
        "description": "America's best-selling SUV does everything well enough to dominate.",
        "pros": [
            "Toyota reliability and resale value",
            "TRD Off-Road trim is surprisingly capable",
            "Spacious for a compact SUV",
        ],
        "cons": [
            "Engine is noisy under acceleration",
            "Interior materials feel basic",
            "Not fun to drive",
        ],
    },
    "Toyota RAV4 Hybrid": {
        "reliability": "5/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.4s",
        "engine": "2.5L I4 Hybrid",
        "driven_wheels": "AWD",
        "est_price_range": "$18k-$25k",
        "ground_clearance": "8.4 in",
        "four_wd_type": "Electronic AWD",
        "tow_capacity": "2,500 lbs",
        "description": "The RAV4 but with 40 mpg and electronic AWD. Basically the default choice.",
        "pros": [
            "~40 mpg combined is outstanding",
            "More power than gas RAV4",
            "Electronic AWD works seamlessly",
        ],
        "cons": [
            "CVT can be noisy under load",
            "Towing drops vs. gas model",
            "Long dealer wait times due to demand",
        ],
    },
    "Volkswagen Atlas": {
        "reliability": "3/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.3s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$18k-$24k",
        "ground_clearance": "8.0 in",
        "four_wd_type": "Full-Time AWD (4MOTION)",
        "tow_capacity": "5,000 lbs",
        "description": "VW's biggest SUV, built for American families who need space.",
        "pros": [
            "Truly spacious three-row interior",
            "Simple, easy-to-use controls",
            "Competitive pricing for its size",
        ],
        "cons": [
            "Turbo four feels strained in a big SUV",
            "VW reliability concerns",
            "Fuel economy is mediocre",
        ],
    },
    "Volkswagen Atlas Cross Sport": {
        "reliability": "3/5",
        "fun_factor": "2/5",
        "zero_to_sixty": "7.1s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$22k-$28k",
        "ground_clearance": "8.0 in",
        "four_wd_type": "Full-Time AWD (4MOTION)",
        "tow_capacity": "5,000 lbs",
        "description": "Two-row Atlas with a sportier roofline and more cargo space.",
        "pros": [
            "More cargo room than three-row Atlas",
            "Sleeker styling with coupe roofline",
            "Same spacious cabin without third row",
        ],
        "cons": [
            "Turbo four is adequate, not quick",
            "No third row limits family appeal",
            "VW reliability is average at best",
        ],
    },
    "Volkswagen Tiguan": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.8s",
        "engine": "2.0L Turbo I4",
        "driven_wheels": "AWD",
        "est_price_range": "$16k-$22k",
        "ground_clearance": "7.9 in",
        "four_wd_type": "Full-Time AWD (4MOTION)",
        "tow_capacity": "1,500 lbs",
        "description": "Compact VW crossover with European handling and available third row.",
        "pros": [
            "Composed handling for a crossover",
            "Available third row for occasional use",
            "Refined ride quality",
        ],
        "cons": [
            "Towing capacity is very low",
            "Interior space trails key rivals",
            "Turbo four is adequate, not exciting",
        ],
    },
    "Volkswagen Tiguan eHybrid": {
        "reliability": "3/5",
        "fun_factor": "3/5",
        "zero_to_sixty": "7.5s",
        "engine": "1.4L Turbo I4 PHEV",
        "driven_wheels": "FWD",
        "est_price_range": "€22k-€30k",
        "ground_clearance": "7.9 in",
        "four_wd_type": None,
        "tow_capacity": "1,500 lbs",
        "description": "European plug-in hybrid Tiguan with ~30 miles of electric range.",
        "pros": [
            "~30 miles EV range for city driving",
            "Smooth hybrid powertrain",
            "Lower running costs in urban use",
        ],
        "cons": [
            "Not available in North America",
            "FWD only limits bad-weather confidence",
            "Battery reduces cargo space slightly",
        ],
    },
}
